-- 코드를 입력하세요

SELECT NB.CATEGORY, NB.BOOK_COUNT TOTAL_SALES
FROM
    (
        SELECT SUM(BS.SALES) BOOK_COUNT, YEAR(BS.SALES_DATE) YEAR, MONTH(BS.SALES_DATE) MONTH, B.CATEGORY CATEGORY
        FROM BOOK_SALES BS
            INNER JOIN BOOK B
            ON B.BOOK_ID = BS.BOOK_ID
        GROUP BY YEAR(BS.SALES_DATE), MONTH(BS.SALES_DATE), B.CATEGORY
    ) NB
WHERE NB.YEAR = 2022 and NB.MONTH = 1
ORDER BY NB.CATEGORY ASC